### ISSUE TITLE
Автор очень очень очень дурка

### ISSUE THREAD

**Issue by Ariollex** [vadim-strebulaev/repa_for_misis#1]
vadim-strebulaev ya smotry anime, da, ya nemnogo ne natural

**Comment by Ariollex** [comment]
он всё понял. Закрываю

**Comment by 5050d0** [comment]
**Таже самая ошибка** 
АВТОР ГДЕ 
![image](https://github.com/vadim-strebulaev/repa_for_misis/assets/153203832/83751f65-47fe-492a-b498-6e2b4e12371d)

**Comment by vadim-strebulaev** [comment]
> он всё понял. Закрываю
ага ага, наглый такой

**Comment by Ariollex** [comment]
Согласен с @5050d0. Действительно, @vadim-strebulaev, где?
